### ISSUE TITLE
Not able to Browse the App

### ISSUE THREAD

**Issue by vinaysandela** [JasonFreeberg/my-spring-app#1]
I tried to implement the same and Not able to see the App on the Azure App Service when browsed. 
Were you able to see on the Web app?
However I am able to see on the local.

**Comment by CyberRedX** [comment]
Yes u are right

**Comment by CyberRedX** [comment]
I don't even know what is this

**Comment by JasonFreeberg** [comment]
@vinaysandela @PokeRealm -- Please see the Azure Docs if you're looking for quickstarts or samples for Java on App Service. This is just my own testing app.

Here are some resources to get you started:
- https://github.com/azure-samples?q=java&type=&language=&sort=
- https://docs.microsoft.com/en-us/azure/app-service/quickstart-java?tabs=javase&pivots=platform-linux
- https://docs.microsoft.com/en-us/azure/app-service/tutorial-java-spring-cosmosdb
- https://docs.microsoft.com/it-it/java/api/overview/azure/maven/azure-webapp-maven-plugin/readme?view=azure-java-stable#quick-start
