### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by CyberRedX** [JasonFreeberg/my-spring-app#2]
Please tell me

**Comment by JasonFreeberg** [comment]
Please see the Azure Docs if you're looking for quickstarts or samples for Java on App Service. This is just my own testing app.

Here are some resources to get you started:
- https://github.com/azure-samples?q=java&type=&language=&sort=
- https://docs.microsoft.com/en-us/azure/app-service/quickstart-java?tabs=javase&pivots=platform-linux
- https://docs.microsoft.com/en-us/azure/app-service/tutorial-java-spring-cosmosdb
- https://docs.microsoft.com/it-it/java/api/overview/azure/maven/azure-webapp-maven-plugin/readme?view=azure-java-stable#quick-start
